name: aqualord
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - jupyterlab
  - kaggle
  - pydrive
  - py3dep
  - pynhd
  - pygeohydro 
  - pydaymet 
  - pygeoogc 
  - pygeoutils
  - async_retriever
  - gdal
  - h5py
  - cartopy
  - future
  - wxpython
  - pyhdf
  - pyresample
  - pip
  - pip:
    - dataretrieval
    - wget
    - smap_io
