name: aqualord
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - jupyterlab
  - kaggle
  - pydrive
  - pygeoogc 
  - pygeoutils
  - py3dep
  - pynhd
  - pygeohydro
  - pydaymet
  - gdal
  - h5py
  - cartopy
  - future
  - wxpython
  - pip:
    - wget
    - pyModis

