name: aqualord
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - jupyterlab
  - kaggle
  - pydrive
  - xarray
  - h5py
  - netcdf4
  - matplotlib
  - gdal
  - future
  - wxpython
  - pip:
    - wget
    - pyModis

